<?php

namespace Ebay\Sell\Marketing\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * This type defines the fields for any warning error messages.
 */
class BaseResponse extends AbstractModel
{
    /**
     * The container for any warning error messages generated by the request. Warnings
     * are not fatal in that they do not prevent the call from running and returning a
     * response, but they should be reviewed to ensure your requests are returning the
     * responses you expect.
     *
     * @var \Ebay\Sell\Marketing\Model\Error[]
     */
    public $warnings = null;
}
