<?php

namespace Ebay\Sell\Marketing\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * This type defines the fields that the call uses to remove ads in bulk.
 */
class BulkDeleteAdRequest extends AbstractModel
{
    /**
     * An array of the listing IDs that identify the ads to remove. <br><br><p
     * class="tablenote"><b>Note:</b> This request accepts both listing IDs, as
     * generated by the Inventory API, and an item IDs, as used in the eBay Traditional
     * API set (e.g., the Trading and Finding APIs).</p>.
     *
     * @var \Ebay\Sell\Marketing\Model\DeleteAdRequest[]
     */
    public $requests = null;
}
