<?php

namespace Ebay\Sell\Marketing\Model;

use OpenAPI\Runtime\AbstractModel;

/**
 * This type defines the fields used in a delete-ad request.
 */
class DeleteAdRequest extends AbstractModel
{
    /**
     * A unique eBay-assigned ID for a listing that is generated when the listing is
     * created.  <p class="tablenote"><b>Note:</b> This request accepts both listing
     * IDs, as generated by the Inventory API, and an item IDs, as used in the eBay
     * Traditional API set (e.g., the Trading and Finding APIs).</p>.
     *
     * @var string
     */
    public $listingId = null;
}
