<?php

namespace Ebay\Sell\Marketing\Api;

use Ebay\Sell\Marketing\Model\Ad as AdModel;
use Ebay\Sell\Marketing\Model\AdIds;
use Ebay\Sell\Marketing\Model\AdPagedCollection;
use Ebay\Sell\Marketing\Model\AdReferences;
use Ebay\Sell\Marketing\Model\Ads;
use Ebay\Sell\Marketing\Model\BulkAdResponse;
use Ebay\Sell\Marketing\Model\BulkCreateAdRequest;
use Ebay\Sell\Marketing\Model\BulkCreateAdsByInventoryReferenceRequest;
use Ebay\Sell\Marketing\Model\BulkCreateAdsByInventoryReferenceResponse;
use Ebay\Sell\Marketing\Model\BulkDeleteAdRequest;
use Ebay\Sell\Marketing\Model\BulkDeleteAdResponse;
use Ebay\Sell\Marketing\Model\BulkDeleteAdsByInventoryReferenceRequest;
use Ebay\Sell\Marketing\Model\BulkDeleteAdsByInventoryReferenceResponse;
use Ebay\Sell\Marketing\Model\CreateAdRequest;
use Ebay\Sell\Marketing\Model\CreateAdsByInventoryReferenceRequest;
use Ebay\Sell\Marketing\Model\DeleteAdsByInventoryReferenceRequest;
use Ebay\Sell\Marketing\Model\UpdateBidPercentageRequest;
use OpenAPI\Runtime\UnexpectedResponse;

class Ad extends AbstractAPI
{
    /**
     * This method adds multiple listings that are managed with the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a> to an existing Promoted Listings campaign. <p>For
     * each listing specified in the request, this method:</p>  <ul><li>Creates an ad
     * for the listing.</li> <li>Sets the bid percentage (also known as the <i>ad
     * rate</i>) for the ad.</li> <li>Associates the ad with the specified
     * campaign.</li></ul>  <p>To create an ad for a listing, specify its
     * <b>inventoryReferenceId</b> and <b>inventoryReferenceType</b>, plus the
     * <b>bidPercentage</b> for the ad in the payload of the request. Specify the
     * campaign to associate the ads to with using the <b>campaign_id</b> path
     * parameter.</p>  <p>In the Inventory API, an <i>inventory reference ID</i> is
     * either a seller-defined <b>SKU</b> value or an <b>inventoryItemGroupKey</b> (a
     * seller-defined ID for a multiple-variation listing).</p>  <p>You can specify a
     * maximum of <b>500 items per call</b> and each campaign can have ads for a
     * maximum of 50,000 items. Be aware when using this call that each variation in a
     * multiple-variation listing creates an individual ad.</p>  <p>Use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/createCampaign">createCampaign</a>
     * to create a new campaign and use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get a list of existing campaigns.</p>.
     *
     * @param string                                   $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                              generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                              href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkCreateAdsByInventoryReferenceRequest $Model       The container for the
     *                                                              bulk request to create ads for eBay inventory reference IDs. eBay inventory
     *                                                              reference IDs are seller-defined IDs used by theInventory API.
     *
     * @return BulkCreateAdsByInventoryReferenceResponse|UnexpectedResponse
     */
    public function bulkCreatesByInventoryReference(string $campaign_id, BulkCreateAdsByInventoryReferenceRequest $Model)
    {
        return $this->request(
        'bulkCreateAdsByInventoryReference',
        'POST',
        "ad_campaign/$campaign_id/bulk_create_ads_by_inventory_reference",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method adds multiple listings to an existing Promoted Listings campaign
     * using <b>listingId</b> values generated by either the <a
     * href="/Devzone/XML/docs/Reference/eBay/index.html" title="Trading API
     * Reference">Trading API</a> or <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>For each listing ID specified in the request,
     * this method:</p>  <ul><li>Creates an ad for the listing.</li> <li>Sets the bid
     * percentage (also known as the <i>ad rate</i>) for the ad.</li> <li>Associates
     * the ad with the specified campaign.</li></ul>  <p>To create an ad for a listing,
     * specify its <b>listingId</b>, plus the <b>bidPercentage</b> for the ad in the
     * payload of the request. Specify the campaign to associate the ads with using the
     * <b>campaign_id</b> path parameter. Listing IDs are generated by eBay when a
     * seller creates listings with the Trading API.</p>  <p>You can specify a maximum
     * of <b>500 listings per call</b> and each campaign can have ads for a maximum of
     * 50,000 items. Be aware when using this call that each variation in a
     * multiple-variation listing creates an individual ad.</p>  <p>Use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/createCampaign">createCampaign</a>
     * to create a new campaign and use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get a list of existing campaigns.</p>.
     *
     * @param string              $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                         generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                         href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkCreateAdRequest $Model       The container for the bulk request to create
     *                                         ads for eBay listing IDs. eBay listing IDs are generated by the Trading API and
     *                                         Inventory API when the listing is created on eBay.
     *
     * @return BulkAdResponse|UnexpectedResponse
     */
    public function bulkCreatesByListingId(string $campaign_id, BulkCreateAdRequest $Model)
    {
        return $this->request(
        'bulkCreateAdsByListingId',
        'POST',
        "ad_campaign/$campaign_id/bulk_create_ads_by_listing_id",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method works with listings created with the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>The method deletes a set of ads, as specified
     * by a list of inventory reference IDs, from the specified campaign. <i>Inventory
     * reference IDs</i> are seller-defined IDs that are used with the Inventory
     * API</a>.</p>  <p>Pass the <b>campaign_id</b> as a path parameter and populate
     * the payload with a list of <b>inventoryReferenceId</b> and
     * <b>inventoryReferenceType</b> pairs that you want to delete.</p>  <p>Get the
     * campaign IDs for a seller by calling <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to get a
     * list of the seller's inventory reference IDs.</p>.
     *
     * @param string                                   $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                              generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                              href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkDeleteAdsByInventoryReferenceRequest $Model       this request object
     *                                                              defines the fields for a <b>bulkDeleteAdsByInventoryReference</b> request
     *
     * @return BulkDeleteAdsByInventoryReferenceResponse|UnexpectedResponse
     */
    public function bulkDeletesByInventoryReference(string $campaign_id, BulkDeleteAdsByInventoryReferenceRequest $Model)
    {
        return $this->request(
        'bulkDeleteAdsByInventoryReference',
        'POST',
        "ad_campaign/$campaign_id/bulk_delete_ads_by_inventory_reference",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method works with listing IDs created with either the <a
     * href="/Devzone/XML/docs/Reference/eBay/index.html" title="Trading API
     * Reference">Trading API</a> or the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>The method deletes a set of ads, as specified
     * by a list of <b>listingID</b> values from a Promoted Listings campaign. A
     * listing ID value is generated by eBay when a seller creates a listing with
     * either the Trading API and Inventory API.</p>  <p>Pass the <b>campaign_id</b> as
     * a path parameter and populate the payload with the set of listing IDs that you
     * want to delete.</p>  <p>Get the campaign IDs for a seller by calling <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to get a
     * list of the seller's inventory reference IDs.</p>.
     *
     * @param string              $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                         generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                         href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkDeleteAdRequest $Model       this request object defines the fields for the
     *                                         <b>bulkDeleteAdsByListingId</b> request
     *
     * @return BulkDeleteAdResponse|UnexpectedResponse
     */
    public function bulkDeletesByListingId(string $campaign_id, BulkDeleteAdRequest $Model)
    {
        return $this->request(
        'bulkDeleteAdsByListingId',
        'POST',
        "ad_campaign/$campaign_id/bulk_delete_ads_by_listing_id",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method works with listings that are managed with the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>. <p>The method updates the <b>bidPercentage</b>
     * values for a set of ads associated with the specified campaign.</p>  <p>Specify
     * the <b>campaign_id</b> as a path parameter and supply a list of
     * <b>inventoryReferenceId</b> and <b>inventoryReferenceType</b> pairs with the
     * updated <b>bidPercentage</b> values in the request body.</p>  <p>In the
     * Inventory API, an <i>inventory reference ID</i> is either a seller-defined
     * <b>SKU</b> value or an <b>inventoryItemGroupKey</b> (a seller-defined ID for a
     * multiple-variation listing).</p>  <p>Get the campaign IDs for a seller by
     * calling <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to get a
     * list of the seller's inventory reference IDs.</p>.
     *
     * @param string                                   $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                              generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                              href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkCreateAdsByInventoryReferenceRequest $Model       this request object
     *                                                              defines the fields for the <b>BulkCreateAdsByInventoryReference</b> request
     *
     * @return BulkCreateAdsByInventoryReferenceResponse|UnexpectedResponse
     */
    public function bulkUpdatesBidByInventoryReference(string $campaign_id, BulkCreateAdsByInventoryReferenceRequest $Model)
    {
        return $this->request(
        'bulkUpdateAdsBidByInventoryReference',
        'POST',
        "ad_campaign/$campaign_id/bulk_update_ads_bid_by_inventory_reference",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method works with listings created with either the <a
     * href="/Devzone/XML/docs/Reference/eBay/index.html" title="Trading API
     * Reference">Trading API</a> or the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>The method updates the <b>bidPercentage</b>
     * values for a set of ads associated with the specified campaign.</p>  <p>Specify
     * the <b>campaign_id</b> as a path parameter and supply a set of listing IDs with
     * their associated updated <b>bidPercentage</b> values in the request body. An
     * eBay listing ID is generated when a listing is created with the Trading API.</p>
     *  <p>Get the campaign IDs for a seller by calling <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to get a
     * list of the seller's inventory reference IDs.</p>.
     *
     * @param string              $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                         generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                         href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param BulkCreateAdRequest $Model       this request object defines the fields for the
     *                                         <b>BulkCreateAdsByListingId</b> request
     *
     * @return BulkAdResponse|UnexpectedResponse
     */
    public function bulkUpdatesBidByListingId(string $campaign_id, BulkCreateAdRequest $Model)
    {
        return $this->request(
        'bulkUpdateAdsBidByListingId',
        'POST',
        "ad_campaign/$campaign_id/bulk_update_ads_bid_by_listing_id",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method retrieves Promoted Listings ads that are associated with listings
     * created with either the <a href="/Devzone/XML/docs/Reference/eBay/index.html"
     * title="Trading API Reference">Trading API</a> or the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>. <p>The method retrieves ads related to the
     * specified campaign. Specify the Promoted Listings campaign to target with the
     * <b>campaign_id</b> path parameter.</p>  <p>Because of the large number of
     * possible results, you can use query parameters to paginate the result set by
     * specifying a <b>limit</b>, which dictates how many ads to return on each page of
     * the response. You can also specify how many ads to skip in the result set before
     * returning the first result using the <b>offset</b> path parameter.</p>  <p>Call
     * <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to retrieve the current campaign IDs for the seller.</p>.
     *
     * @param string $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                            generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                            href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param array  $queries     options:
     *                            'limit'	string	Specifies the maximum number of ads to return on a page in the
     *                            paginated response. <p><b>Default: </b>10 <br><b>Maximum:</b> 500</p>
     *                            'listing_ids'	string	A comma separated list of listing IDs. The response
     *                            includes only active ads (ads associated with a RUNNING campaign). The results
     *                            do not include listing IDs that are excluded by other conditions.
     *                            'offset'	string	Specifies the number of ads to skip in the result set before
     *                            returning the first ad in the paginated response.  <p>Combine <b>offset</b> with
     *                            the <b>limit</b> query parameter to control the items returned in the response.
     *                            For example, if you supply an <b>offset</b> of <code>0</code> and a <b>limit</b>
     *                            of <code>10</code>, the first page of the response contains the first 10 items
     *                            from the complete list of items retrieved by the call. If <b>offset</b> is
     *                            <code>10</code> and <b>limit</b> is <code>20</code>, the first page of the
     *                            response contains items 11-30 from the complete result set.</p>
     *                            <p><b>Default:</b> 0</p>
     *
     * @return AdPagedCollection|UnexpectedResponse
     */
    public function gets(string $campaign_id, array $queries = [])
    {
        return $this->request(
        'getAds',
        'GET',
        "ad_campaign/$campaign_id/ad",
        null,
        $queries,
        []
        );
    }

    /**
     * This method works with listings created with either the <a
     * href="/Devzone/XML/docs/Reference/eBay/index.html" title="Trading API
     * Reference">Trading API</a> or the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>. <p>The method:</p> <ul><li>Creates an ad for the
     * specified listing ID.</li> <li>Sets the bid percentage (also known as the "ad
     * rate") for the ad.</li> <li>Associates the ad with the specified
     * campaign.</li></ul>  <p>To create an ad for a listing, specify its
     * <b>listingId</b>, plus the <b>bidPercentage</b> for the ad in the payload of the
     * request. Specify the campaign to associate the ad with using the
     * <b>campaign_id</b> path parameter. Listing IDs are generated by eBay when a
     * seller creates listings with the Trading API or Inventory API.</p>  <p>Each
     * campaign can have ads for a maximum of 50,000 items, and each item in a
     * multiple-variation listing is considered as an single item.</p>  <p>Use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/createCampaign">createCampaign</a>
     * to create a new campaign and use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get a list of existing campaigns.</p>.
     *
     * @param string          $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                     generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                     href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param CreateAdRequest $Model       this request object defines the fields used in the
     *                                     <b>createAdByListingId</b> request
     *
     * @return object|UnexpectedResponse
     */
    public function createByListingId(string $campaign_id, CreateAdRequest $Model)
    {
        return $this->request(
        'createAdByListingId',
        'POST',
        "ad_campaign/$campaign_id/ad",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method works with listings that are managed with the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>The method:</p> <ul><li>Creates an ad for the
     * specified listing.</li> <li>Sets the bid percentage (also known as the "ad
     * rate") for the ad.</li> <li>Associates the ad with the specified
     * campaign.</li></ul>  <p>To create an ad for a listing, specify its
     * <b>inventoryReferenceId</b> and <b>inventoryReferenceType</b>, plus the
     * <b>bidPercentage</b> for the ad in the payload of the request. Specify the
     * campaign to associate the ad with using the <b>campaign_id</b> path
     * parameter.</p>  <p>In the Inventory API, an <i>inventory reference ID</i> is
     * either a seller-defined <b>SKU</b> value or an <b>inventoryItemGroupKey</b> (a
     * seller-defined ID for a multiple-variation listing).</p>  <p>Each campaign can
     * have ads for a maximum of 50,000 items, and each item in a multiple-variation
     * listing is considered as an individual item.</p>  <p>Use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/createCampaign">createCampaign</a>
     * to create a new campaign and use <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get a list of existing campaigns.</p>.
     *
     * @param string                               $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                          generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                          href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param CreateAdsByInventoryReferenceRequest $Model       this request object defines
     *                                                          the fields used in the <b>createAdsByInventoryReference</b> request
     *
     * @return AdReferences|UnexpectedResponse
     */
    public function createsByInventoryReference(string $campaign_id, CreateAdsByInventoryReferenceRequest $Model)
    {
        return $this->request(
        'createAdsByInventoryReference',
        'POST',
        "ad_campaign/$campaign_id/create_ads_by_inventory_reference",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method retrieves the specified ad from the specified campaign.  <p>In the
     * request, supply the <b>campaign_id</b> and <b>ad_id</b> as path parameters.</p>
     * <p>Call <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to retrieve a list of the seller's current campaign IDs and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to
     * retrieve their current ad IDs.</p>.
     *
     * @param string $ad_id       Identifier of an ad. This ID was generated when the ad was
     *                            created.
     * @param string $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                            generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                            href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     *
     * @return AdModel|UnexpectedResponse
     */
    public function get(string $ad_id, string $campaign_id)
    {
        return $this->request(
        'getAd',
        'GET',
        "ad_campaign/$campaign_id/ad/$ad_id",
        null,
        [],
        []
        );
    }

    /**
     * This method removes the specified ad from the specified campaign.  <p>Pass the
     * ID of the ad to delete with the ID of the campaign associated with the ad as
     * path parameters to the call.</p> <p>Call <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get the current list of the seller's campaign IDs.</p>.
     *
     * @param string $ad_id       Identifier of an ad. This ID was generated when the ad was
     *                            created.
     * @param string $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                            generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                            href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     *
     * @return UnexpectedResponse
     */
    public function delete(string $ad_id, string $campaign_id): UnexpectedResponse
    {
        return $this->request(
        'deleteAd',
        'DELETE',
        "ad_campaign/$campaign_id/ad/$ad_id",
        null,
        [],
        []
        );
    }

    /**
     * This method works with listings that are managed with the <a
     * href="/api-docs/sell/inventory/resources/methods" title="Inventory API
     * Reference">Inventory API</a>.  <p>The method deletes ads using a list of
     * seller-defined inventory reference IDs, used with the Inventory API, that are
     * associated with the specified campaign ID.</p> <p>Specify the campaign ID (as a
     * path parameter) and a list of <b>inventoryReferenceId</b> and
     * <b>inventoryReferenceType</b> pairs to be deleted.</p>  <p>Call <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to get a list of the seller's current campaign IDs.</p>.
     *
     * @param string                               $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                          generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                          href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param DeleteAdsByInventoryReferenceRequest $Model       this request object defines
     *                                                          the fields for the <b>deleteAdsByInventoryReference</b> request
     *
     * @return AdIds|UnexpectedResponse
     */
    public function deletesByInventoryReference(string $campaign_id, DeleteAdsByInventoryReferenceRequest $Model)
    {
        return $this->request(
        'deleteAdsByInventoryReference',
        'POST',
        "ad_campaign/$campaign_id/delete_ads_by_inventory_reference",
        $Model->getArrayCopy(),
        [],
        []
        );
    }

    /**
     * This method retrieves Promoted Listings ads associated with listings that are
     * managed with the <a href="/api-docs/sell/inventory/resources/methods"
     * title="Inventory API Reference">Inventory API</a> from the specified campaign.
     * <p>Supply the <b>campaign_id</b> as a path parameter and use query parameters to
     * specify the <b>inventory_reference_id</b> and <b>inventory_reference_type</b>
     * pairs.</p>  <p>In the Inventory API, an <i>inventory reference ID</i> is either
     * a seller-defined <b>SKU</b> value or an <b>inventoryItemGroupKey</b> (a
     * seller-defined ID for an inventory item group, which is an entity that's used in
     * the Inventory API to create a multiple-variation listing). To indicate a listing
     * managed by the Inventory API, you must always specify both an
     * <b>inventory_reference_id</b> and the associated
     * <b>inventory_reference_type</b>.</p>  <p>Call <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to retrieve all of the seller's the current campaign IDs.</p>.
     *
     * @param string $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                            generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                            href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param array  $queries     options:
     *                            'inventory_reference_id'	string	The inventory reference ID associated with the
     *                            ad you want returned. A seller's inventory reference ID is the ID of either a
     *                            listing or the ID of an inventory item group (the parent of a multi-variation
     *                            listing, such as a shirt that is available in multiple sizes and colors). You
     *                            must always supply in both an <b>inventory_reference_id</b> and an
     *                            <b>inventory_reference_type</b>.
     *                            'inventory_reference_type'	string	The type of the inventory reference ID. Set
     *                            this value to either <code>INVENTORY_ITEM</CODE> (a single listing) or
     *                            <code>INVENTORY_ITEM_GROUP</CODE> (a multi-variation listing). You must always
     *                            pass in both an <b>inventory_reference_id</b> and an
     *                            <b>inventory_reference_type</b>.
     *
     * @return Ads|UnexpectedResponse
     */
    public function getsByInventoryReference(string $campaign_id, array $queries = [])
    {
        return $this->request(
        'getAdsByInventoryReference',
        'GET',
        "ad_campaign/$campaign_id/get_ads_by_inventory_reference",
        null,
        $queries,
        []
        );
    }

    /**
     * This method updates the bid percentage (also known as the "ad rate") for the
     * specified ad in the specified campaign. <p>In the request, supply the
     * <b>campaign_id</b> and <b>ad_id</b> as path parameters, and supply the new
     * <b>bidPercentage</b> value in the payload of the call.</p>  <p>Call <a
     * href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>
     * to retrieve a seller's current campaign IDs and call <a
     * href="/api-docs/sell/marketing/resources/ad/methods/getAds">getAds</a> to get
     * their ad IDs.</p>.
     *
     * @param string                     $ad_id       a unique eBay-assigned ID for an ad that's generated when
     *                                                an ad is created
     * @param string                     $campaign_id A unique eBay-assigned ID for an ad campaign that's
     *                                                generated when a campaign is created. Get a seller's campaign IDs by calling <a
     *                                                href="/api-docs/sell/marketing/resources/campaign/methods/getCampaigns">getCampaigns</a>.
     * @param UpdateBidPercentageRequest $Model       this type defines the fields for the
     *                                                <b>updateBid</b> request
     *
     * @return UnexpectedResponse
     */
    public function updateBid(string $ad_id, string $campaign_id, UpdateBidPercentageRequest $Model): UnexpectedResponse
    {
        return $this->request(
        'updateBid',
        'POST',
        "ad_campaign/$campaign_id/ad/$ad_id/update_bid",
        $Model->getArrayCopy(),
        [],
        []
        );
    }
}
